# Matugen Configuration

[config]
reload_apps = true
set_wallpaper = false
type = "scheme-expressive"
contrast = 0

[config.reload_apps_list.hyprland]
hook = "hyprctl reload"

[config.reload_apps_list.kitty]
hook = "killall -SIGUSR1 kitty"

[config.reload_apps_list.rofi]
hook = "pkill rofi"

[config.reload_apps_list.swaync]
hook = "/home/michal/.config/swaync/reload_swaync.sh"

[config.reload_apps_list.quickshell]
hook = "/home/michal/.config/scripts/qs_manager.sh restart"

[templates.colors]
input_path = "/home/michal/.config/matugen/templates/colors.conf"
output_path = "/home/michal/.config/hypr/colors.conf"

[templates.kitty]
input_path = "/home/michal/.config/matugen/templates/kitty.conf"
output_path = "/home/michal/.config/kitty/current-theme.conf"

[templates.p10k]
input_path = "/home/michal/.config/matugen/templates/p10k-colors.zsh"
output_path = "/home/michal/.config/p10k-colors.zsh"

[templates.rofi]
input_path = "/home/michal/.config/matugen/templates/rofi-colors.rasi"
output_path = "/home/michal/.config/rofi/shared/colors.rasi"

[templates.quickshell]
input_path = "/home/michal/.config/matugen/templates/colors.json"
output_path = "/home/michal/.config/quickshell/config.json"

[templates.swaync]
input_path = "/home/michal/.config/matugen/templates/swaync-colors.css"
output_path = "/home/michal/.config/swaync/matugen-colors.css"

[templates.discord]
input_path = "/home/michal/.config/matugen/templates/discord.css"
output_path = "/home/michal/.config/BetterDiscord/themes/matugen.theme.css"
