# ============================================
# Powerlevel10k Colors - Generated by Matugen
# JASKRAWE i RÓŻNORODNE kolory!
# ============================================
# Source this file AFTER your .p10k.zsh config

# Prompt character colors - BARDZO JASNE
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#{{colors.primary.default.hex_stripped}}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#{{colors.error.default.hex_stripped}}'

# Directory colors - JASKRAWE kolory dla lepszej widoczności
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#{{colors.primary.default.hex_stripped}}'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#{{colors.secondary.default.hex_stripped}}'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#{{colors.tertiary.default.hex_stripped}}'

# Directory states - RÓŻNE JASKRAWE kolory dla różnych stanów
typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='#{{colors.error.default.hex_stripped}}'
typeset -g POWERLEVEL9K_DIR_NON_EXISTENT_FOREGROUND='#{{colors.on_error_container.default.hex_stripped}}'

# Home directory - WYRÓŻNIONY kolor
typeset -g POWERLEVEL9K_HOME_FOREGROUND='#{{colors.on_tertiary_container.default.hex_stripped}}'
typeset -g POWERLEVEL9K_HOME_SUBFOLDER_FOREGROUND='#{{colors.tertiary.default.hex_stripped}}'

# Special directories
typeset -g POWERLEVEL9K_ETC_FOREGROUND='#{{colors.on_secondary_container.default.hex_stripped}}'

# Git status colors - WYRAZISTE różnice
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#{{colors.on_primary_container.default.hex_stripped}}'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#{{colors.on_secondary_container.default.hex_stripped}}'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#{{colors.on_error_container.default.hex_stripped}}'

# Command execution time
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#{{colors.on_surface.default.hex_stripped}}'

# Status colors
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#{{colors.on_primary_container.default.hex_stripped}}'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#{{colors.error.default.hex_stripped}}'

# Background jobs
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#{{colors.on_tertiary_container.default.hex_stripped}}'

# Context (user@host)
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#{{colors.on_surface.default.hex_stripped}}'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#{{colors.error.default.hex_stripped}}'

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#{{colors.secondary.default.hex_stripped}}'

# Export colors for use in scripts
export MATUGEN_PRIMARY='#{{colors.primary.default.hex_stripped}}'
export MATUGEN_SECONDARY='#{{colors.secondary.default.hex_stripped}}'
export MATUGEN_TERTIARY='#{{colors.tertiary.default.hex_stripped}}'
export MATUGEN_ERROR='#{{colors.error.default.hex_stripped}}'
export MATUGEN_SURFACE='#{{colors.surface.default.hex_stripped}}'
export MATUGEN_ON_SURFACE='#{{colors.on_surface.default.hex_stripped}}'
export MATUGEN_ON_SURFACE_VARIANT='#{{colors.on_surface_variant.default.hex_stripped}}'
export MATUGEN_OUTLINE='#{{colors.outline.default.hex_stripped}}'

# ============================================
# LS_COLORS - JASKRAWE kolory dla ls (runtime conversion)
# ============================================
_hex_to_rgb() {
    local hex=$1
    printf "%d;%d;%d" 0x${hex:0:2} 0x${hex:2:2} 0x${hex:4:2}
}

# Katalogi - PRIMARY (jasny niebieski/główny kolor)
local dir_rgb=$(_hex_to_rgb "{{colors.primary.default.hex_stripped}}")
# Pliki tekstowe - ON_SURFACE (jasny biały/czytelny)
local file_rgb=$(_hex_to_rgb "{{colors.on_surface.default.hex_stripped}}")
# Symlinki - TERTIARY (jasny pomarańczowy/akcent)
local link_rgb=$(_hex_to_rgb "{{colors.tertiary.default.hex_stripped}}")
# Executable - SECONDARY (jasny fioletowy/różowy)
local exec_rgb=$(_hex_to_rgb "{{colors.secondary.default.hex_stripped}}")
# Archiwa - ON_TERTIARY_CONTAINER (jasny beżowy)
local archive_rgb=$(_hex_to_rgb "{{colors.on_tertiary_container.default.hex_stripped}}")
# Obrazy - ON_PRIMARY_CONTAINER (jasny lawendowy)
local image_rgb=$(_hex_to_rgb "{{colors.on_primary_container.default.hex_stripped}}")
# Multimedia - ERROR (jasny czerwony/różowy)
local media_rgb=$(_hex_to_rgb "{{colors.error.default.hex_stripped}}")
# Dokumenty - ON_SECONDARY_CONTAINER (jasny fioletowy)
local doc_rgb=$(_hex_to_rgb "{{colors.on_secondary_container.default.hex_stripped}}")

export LS_COLORS="di=01;38;2;${dir_rgb}:"\
"fi=00;38;2;${file_rgb}:"\
"ln=01;38;2;${link_rgb}:"\
"ex=01;38;2;${exec_rgb}:"\
"*.zip=00;38;2;${archive_rgb}:"\
"*.tar=00;38;2;${archive_rgb}:"\
"*.gz=00;38;2;${archive_rgb}:"\
"*.7z=00;38;2;${archive_rgb}:"\
"*.rar=00;38;2;${archive_rgb}:"\
"*.jpg=00;38;2;${image_rgb}:"\
"*.jpeg=00;38;2;${image_rgb}:"\
"*.png=00;38;2;${image_rgb}:"\
"*.gif=00;38;2;${image_rgb}:"\
"*.svg=00;38;2;${image_rgb}:"\
"*.webp=00;38;2;${image_rgb}:"\
"*.mp4=00;38;2;${media_rgb}:"\
"*.mkv=00;38;2;${media_rgb}:"\
"*.mp3=00;38;2;${media_rgb}:"\
"*.flac=00;38;2;${media_rgb}:"\
"*.wav=00;38;2;${media_rgb}:"\
"*.pdf=00;38;2;${doc_rgb}:"\
"*.doc=00;38;2;${doc_rgb}:"\
"*.docx=00;38;2;${doc_rgb}:"\
"*.txt=00;38;2;${doc_rgb}"
