animations {
    enabled = true

    bezier = workspaces, 0.34, 1.26, 0.44, 1
    bezier = windows, 0.35, 1.14, 0.44, 1

    animation = workspaces, 1, 5, workspaces, slidefade
    animation = windows, 1, 5, windows, popin 70%
}