exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpm reload -n
exec-once = swaync -c & awww-daemon & hypridle & ~/.config/hypr/xdg.sh &
exec-once = ~/.config/scripts/wallpaper-thumbs.sh &
# Zlecamy start całego UI managerowi (on wie co robi)
exec-once = ~/.config/scripts/qs_manager.sh restart
