hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("awww-daemon & hypridle & ~/dotfiles/hyprland/.config/hypr/xdg.sh")
    hl.exec_cmd("~/.config/quickshell/wallpaper-thumbs.sh")
    hl.exec_cmd("~/.config/scripts/qs_manager.sh restart")
    hl.exec_cmd("~/.config/scripts/usb.sh")
    hl.exec_cmd("~/.config/scripts/check_updates.sh")
end)
