exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpm reload -n
exec-once = awww-daemon & hypridle & ~/dotfiles/hyprland/.config/hypr/xdg.sh
exec-once = ~/.config/quickshell/wallpaper-thumbs.sh
exec-once = ~/.config/scripts/qs_manager.sh restart
