exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpm reload -n
exec-once = swaync -c & awww-daemon & hypridle & ~/dotfiles/hyprland/.config/hypr/xdg.sh
#exec-once = eww --config ~/.config/eww/bar daemon
#exec-once = sleep 2 && ~/.config/eww/bar/launch_bar.sh --force-open
exec-once = ~/.config/quickshell/wallpaper-thumbs.sh
exec-once = env QS_NO_RELOAD_POPUP=1 quickshell -p ~/.config/quickshell/TopBar/TopBar.qml