decoration {
    rounding = 4
    
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = yes
        xray = true
    }

    shadow {
        enabled = false
    }
}

    
