xwayland {
    force_zero_scaling = true
}

general {
    border_size = 3

    col.active_border = $primary $secondary 120deg
    col.inactive_border = $primary_container

    resize_on_border = true

    gaps_in = 4
    gaps_out = 8

    layout = dwindle

    allow_tearing = false
}

dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

# master {

#     # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
#     new_is_master = true
# }

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gesture = 3, horiz, workspace, m+1, m-1
}

misc {
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    vfr = false # Keep redraw cadence stable for layer-shell apps (eww/swaync)
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
