source = ./variables.conf
source = ./bindings.conf
source = ./animations.conf
source = ./decorations.conf
source = ./colors.conf
source = ./general.conf
source = ./input.conf
source = ./autostart.conf
source = ./workspaces.conf
source = ./window-rules.conf
# Monitors configured via nwg-displays (probably will be replaced by smth else in the future)
source = ./monitors.conf
source = ./env.conf
source = ./plugins.conf
