input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    kb_options =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        tap-to-click = true
        tap-and-drag = true
    }

    sensitivity = 0
}
