env = LANG,pl_PL.UTF-8
env = LANGUAGE, pl_PL:pl
env = LC_ALL, pl_PL.UTF-8

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun -show-icons
$emoji = $HOME/.config/rofi/emoji-picker/rofi-emoji-picker.sh
$browser = zen-browser
$editor = code
$music = spotify
$mainMod = super
