$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun -show-icons
$emoji = $HOME/.config/rofi/emoji-picker/rofi-emoji-picker.sh
$browser = zen-browser
$editor = code
$music = spotify
$mainMod = super
