-- Generated by nwg-displays on 2026-04-20 at 00:53:14. Do not edit manually.

for i = 1, 4 do
	hl.workspace_rule({ workspace = tostring(i), monitor = "DP-2", default = (i == 1) })
end

for i = 5, 8 do
	hl.workspace_rule({ workspace = tostring(i), monitor = "DP-3", default = (i == 5) })
end
