# OneDarkPro Colors for Kitty

# Background and foreground
background #1e1e2e
foreground #cdd6f4

# Base colors
color0 #45475a
color1 #e3242b
color2 #03c04a
color3 #daa520
color4 #346bc0
color5 #4b0082
color6 #4b8d75
color7 #cdd6f4

# Bright colors
color8 #7f849c
color9 #cf1020
color10 #a6e3a1
color11 #fffd37
color12 #4ac8ff
color13 #9932cc
color14 #94e2d5
color15 #f5e0dc

# Cursor and selection
cursor #cdd6f4
selection_background #45475a
selection_foreground #cdd6f4
